### ISSUE TITLE
Specialize FAST

### ISSUE THREAD

**Issue by firejake308** [firejake308/code-versus-bugs#74]
I think FAST should be specialized so that it fills in the tank niche. We should increase damage so that it'll one-hit even beefy malware like Trojans and Worms, but we should heavily nerf its attack speed so that it is absolutely useless against anything that moves. That way, FAST will feel less like the disc thrower and more like its own thing.

**Comment by patrickkenney9801** [comment]
It is called fast...perhaps we should create a new tower known as
Technologically Advanced NK?

**Comment by firejake308** [comment]
Well, Patrick, there's this thing called sarcasm.... Anyway, if you don't
like that idea, what about bomb tower? Do we need 2 wave-clear towers
(scanner and bomb)?

**Comment by patrickkenney9801** [comment]
The difference between the Scanner and Bomb Tower are quite significant.
First of all, the Scanner is completely useless since you nerfed it and now
only helps by identifying Trojans.  Second, a Bomb Tower has a much
different firing mechanism and has a much greater range, due to a Scanners
lack of range they are severely set back and their rotations are too weak
to actually achieve anything at all.

**Comment by firejake308** [comment]
Well, Patrick, we can't have towers that have been nerfed to non-existence,
now can we? Take your game-balancing skills that you acquired over your
3000 hours of RuneScape and put them to use to fix up the Scanner. Whenever
you can.

**Comment by firejake308** [comment]
But, seriously, what abou the sarcasm take. We call it FAST, but then it
turns out to be really slow. We can warn the player in one of the pre-round
info pop-ups. DO IT FOR THE LULZ!

**Comment by patrickkenney9801** [comment]
Lol maybe.

**Comment by firejake308** [comment]
Done. Let the Trolling begin!
